package json.resources

import io.circe.generic.JsonCodec
import io.circe.generic.extras.{Configuration, ConfiguredJsonCodec, JsonKey}
import json.resources.TypeDefinitions._

object ADT {
  implicit val config: Configuration = Configuration.default


  @JsonCodec final case class ExportJson(data: List[List[String]])

  @JsonCodec final case class PropertyOwner(owner: UserData)

  @JsonCodec final case class UserData(
                                        ID: Int,
                                        user_login: String,
                                        user_pass: String,
                                        user_nicename: String,
                                        user_email: String,
                                        user_url: String,
                                        user_registered: String,
                                        user_activation_key: String,
                                        user_status: String,
                                        display_name: String,
                                        user_meta: UserMeta,
                                        properties: Option[Map[String, PropertyRecord]]
                                      )

  @JsonCodec final case class UserMeta(
                                        nickname: OptionalList[String],
                                        first_name: OptionalList[String],
                                        last_name: OptionalList[String],
                                        wp_user_level: OptionalList[Int],
                                        bhome_switch_notification: OptionalList[String],
                                        company_data: OptionalList[String],
                                        company_name: OptionalList[String],
                                        company_phone: OptionalList[String],
                                        company_street: OptionalList[String],
                                        company_city: OptionalList[String],
                                        company_zip: OptionalList[String],
                                        bhome_password_changed: OptionalList[String],
                                        bhome_password_date: OptionalList[String],
                                        ms_inquiry_first_name: OptionalList[String],
                                        ms_inquiry_last_name: OptionalList[String],
                                        ms_inquiry_email: OptionalList[String]
                                      )

  @JsonCodec final case class PropertyRecord(
                                              property_data: PropertyData,
                                              comment: Option[Map[String, Option[Comments]]],
                                              //comment_meta:      Option[Map[String, Option[CommentMetaData]]], empty ones are as lists, others as maps. Example: 103.json
                                              calendar_data: Option[List[Option[CalendarData]]],
                                              conversation_data: Option[Map[String, Option[ConversationData]]]
                                            )

  @JsonCodec final case class PropertyData(
                                            property_id: Int,
                                            property_fields: PropertyFields
                                          )

  @ConfiguredJsonCodec final case class PropertyFields(
                                                        post_title: OptionalList[String],
                                                        post_content: OptionalList[String],
                                                        post_parent: OptionalList[Int],
                                                        post_status: OptionalList[String],
                                                        post_url: OptionalList[String],
                                                        //taxonomies:                    Taxonomies,
                                                        @JsonKey("prop-nickname") prop_nickname: OptionalList[String],
                                                        listCalendar: OptionalList[String],
                                                        created_by: OptionalList[String],
                                                        featured_property: OptionalList[String],
                                                        @JsonKey("License-variant") License_variant: OptionalList[String],
                                                        @JsonKey("License-text") License_text: OptionalList[String],
                                                        @JsonKey("User-Name-BH") User_Name_BH: OptionalList[String],
                                                        @JsonKey("User-SurName-BH") User_SurName_BH: OptionalList[String],
                                                        @JsonKey("E-Mail-BH") E_Mail_BH: OptionalList[String],
                                                        phone_full: OptionalList[String],
                                                        owner_site: OptionalList[String],
                                                        owner_name: OptionalList[String],
                                                        owner_email: OptionalList[String],
                                                        owner_login: OptionalList[String],
                                                        //bedrooms-BH:                   OptionalList[String],
                                                        //bedrooms-BH-Number:            OptionalList[String],
                                                        //bedTyle-BH:                    OptionalList[String],
                                                        //kitchen-BH:                    OptionalList[String],
                                                        //accomodates-BH:                OptionalList[String],
                                                        //accomodates-BH-Number:         OptionalList[String],
                                                        //bathroom-BH:                   OptionalList[String],
                                                        //petFriendly-BH:                OptionalList[String],
                                                        //internet-BH:                   OptionalList[String],
                                                        //rates-BH:                      OptionalList[String],
                                                        //view-BH:                       OptionalList[String],
                                                        //notes-BH:                      OptionalList[String],
                                                        kid_friendly_description: OptionalList[String],
                                                        amenities: OptionalList[String],
                                                        published_per_night: OptionalList[String],
                                                        published_per_night_currency: OptionalList[String],
                                                        property_type: OptionalList[String],
                                                        published_min_stay: OptionalList[String],
                                                        headline: OptionalList[String],
                                                        what_we_like_title: OptionalList[String],
                                                        //what-we-like:                  OptionalList[String],
                                                        pool_exists: OptionalList[String],
                                                        kid_friendly: OptionalList[String],
                                                        price_is_per_night: OptionalList[String],
                                                        net_checkbox: OptionalList[String],
                                                        available_for_rent_check: OptionalList[String],
                                                        //pool-BH:                       OptionalList[String],
                                                        country: OptionalList[String],
                                                        //prop-inv-name:                 OptionalList[String],
                                                        rates_table: OptionalList[String],
                                                        byline_as_link: OptionalList[String],
                                                        hi_res_images: OptionalList[String],
                                                        first_booking_notification: OptionalList[String],
                                                        new_interface: OptionalList[String],
                                                        excerpt_special: OptionalList[String],
                                                        show_rates_table: OptionalList[String],
                                                        seo_link_footer_region: OptionalList[String],
                                                        seo_link_footer_subregion: OptionalList[String],
                                                        seo_link_footer_city: OptionalList[String],
                                                        show_rates_table_editor: OptionalList[String],
                                                        boutiqueContact: OptionalList[String],
                                                        client_image_upload_done: OptionalList[String],
                                                        show_floor_plans: OptionalList[String],
                                                        autoaccept: OptionalList[String],
                                                        around_with_description: OptionalList[String],
                                                        no_past_events: OptionalList[String],
                                                        no_around: OptionalList[String],
                                                        influencer: OptionalList[String],
                                                        social: OptionalList[String],
                                                        no_exterior: OptionalList[String],
                                                        dollar_value: OptionalList[String],
                                                        trello: OptionalList[String],
                                                        //paypal_data:                   OptionalList[String],
                                                        ms_facts_hunter: OptionalList[String],
                                                        bhome_able_to_rent: OptionalList[String],
                                                        bhome_personal_or_business: OptionalList[String],
                                                        bhome_presented_as_hotel: OptionalList[String],
                                                        bhome_images_available: OptionalList[String],
                                                        bhome_amount_of_sites: OptionalList[String],
                                                        bhome_contact_person: OptionalList[String],
                                                        bhome_owner_website: OptionalList[String],
                                                        ms_facts_gps_descr: OptionalList[String],
                                                        ms_facts_bedrooms: OptionalList[String],
                                                        ms_facts_bedrooms_descr: OptionalList[String],
                                                        ms_facts_bed_types: OptionalList[String],
                                                        ms_facts_bed_types_descr: OptionalList[String],
                                                        ms_facts_accomodate: OptionalList[String],
                                                        ms_facts_accomodate_descr: OptionalList[String],
                                                        ms_facts_bathrooms: OptionalList[String],
                                                        ms_facts_bathrooms_descr: OptionalList[String],
                                                        ms_facts_amenities: OptionalList[String],
                                                        ms_facts_amenities_descr: OptionalList[String],
                                                        ms_facts_rates: OptionalList[String],
                                                        ms_facts_rates_descr: OptionalList[String],
                                                        ms_facts_check_in: OptionalList[String],
                                                        ms_facts_check_in_descr: OptionalList[String],
                                                        ms_facts_deposit: OptionalList[String],
                                                        ms_facts_deposit_descr: OptionalList[String],
                                                        ms_facts_cancelation: OptionalList[String],
                                                        ms_facts_cancelation_descr: OptionalList[String],
                                                        ms_facts_min_stay: OptionalList[String],
                                                        ms_facts_min_stay_descr: OptionalList[String],
                                                        ms_facts_pets: OptionalList[String],
                                                        ms_facts_pets_descr: OptionalList[String],
                                                        ms_facts_kids: OptionalList[String],
                                                        ms_facts_kids_descr: OptionalList[String],
                                                        ms_facts_airport: OptionalList[String],
                                                        ms_facts_airport_descr: OptionalList[String],
                                                        ms_facts_visit_best: OptionalList[String],
                                                        ms_facts_visit_best_descr: OptionalList[String],
                                                        ms_facts_notes: OptionalList[String],
                                                        ms_facts_notes_descr: OptionalList[String],
                                                        ms_facts_influencer: OptionalList[String],
                                                        ms_facts_social: OptionalList[String],
                                                        bhome_facts_other_sites: OptionalList[String],
                                                        bhome_facts_other_sites_descr: OptionalList[String],
                                                        ms_facts_around: OptionalList[String],
                                                        ms_facts_history: OptionalList[String],
                                                        ms_facts_architect: OptionalList[String],
                                                        ms_facts_press: OptionalList[String],
                                                        ms_facts_seo: OptionalList[String],
                                                        //bhome_property_title:        OptionalList[String],
                                                        ms_facts_exterior: OptionalList[String],
                                                        ms_facts_interior: OptionalList[String],
                                                        site_one: OptionalList[String],
                                                        region: OptionalList[String],
                                                        town: OptionalList[String],
                                                        _yoast_wpseo_title: OptionalList[String],
                                                        _yoast_wpseo_metadesc: OptionalList[String],
                                                        has_events: OptionalList[String],
                                                        //Thumb-Text:                  OptionalList[String],
                                                        //Google-Maps-Lat:             OptionalList[String],
                                                        //Google-Maps-Lan:             OptionalList[String],
                                                        //Google-Maps-Zoom:            OptionalList[String],
                                                        //address_components:          OptionalList[String],
                                                        //closest_properties:          Option[List[Map[String, Map[String, String]]]],
                                                        //upload_main_image:           OptionalList[String],
                                                        bhome_property_slider: OptionalList[String],
                                                        //upload_exterior_image:       OptionalList[String],
                                                        //upload_interior_image:       OptionalList[String],
                                                        //upload_slider_image:         OptionalList[String],
                                                        //text_image_ma:               OptionalList[String],
                                                        //text_image_ex:               OptionalList[String],
                                                        //text_image_in:               OptionalList[String],
                                                        //text_image_th:               OptionalList[String],
                                                        //text_image_slider:           OptionalList[String],
                                                        //text_image_in_desc:          OptionalList[String],
                                                        //text_image_ex_desc:          OptionalList[String],
                                                        //ms_search_autocomplete:      OptionalList[String],
                                                        agreement_name: OptionalList[String],
                                                        agreement_date: OptionalList[String],
                                                        //_thumbnail_id:               OptionalList[String],
                                                        security_deposit: OptionalList[String],
                                                        security_deposit_check: OptionalList[String],
                                                        check_in: OptionalList[String],
                                                        check_out: OptionalList[String],
                                                        cancellation: OptionalList[String],
                                                        bhome_add_quests_persons: OptionalList[String],
                                                        //additional_fees:             OptionalList[String],
                                                        second_contact: OptionalList[String],
                                                        bhome_invoice_name: OptionalList[String],
                                                        bhome_invoice_surname: OptionalList[String],
                                                        bhome_invoice_email: OptionalList[String],
                                                        //bhome_season:                OptionalList[String],
                                                        behome_description_title: OptionalList[String],
                                                        price_is_per_week: OptionalList[String],
                                                        traveler_notes: OptionalList[String],
                                                        security_deposit_percentage: OptionalList[String],
                                                        tax_rate_check: OptionalList[String],
                                                        tax_rate_check_person: OptionalList[String],
                                                        tax_rate: OptionalList[String],
                                                        tax_rate_person: OptionalList[String],
                                                        no_taxes_check: OptionalList[String],
                                                        bhome_rate_from: OptionalList[String],
                                                        bhome_rate_to: OptionalList[String],
                                                        price_is_per_month: OptionalList[String],
                                                        bhome_changover_check: OptionalList[String],
                                                        bhome_changover_day: OptionalList[String],
                                                        bhome_diff_weeknd_check: OptionalList[String],
                                                        bhome_diff_weeknd_rate: OptionalList[String],
                                                        bhome_diff_weeknd_thu: OptionalList[String],
                                                        bhome_diff_weeknd_fri: OptionalList[String],
                                                        bhome_diff_weeknd_sat: OptionalList[String],
                                                        bhome_diff_weeknd_sun: OptionalList[String],
                                                        bhome_add_quests_check: OptionalList[String],
                                                        bhome_add_quests_rate: OptionalList[String],
                                                        bhome_add_quests_period: OptionalList[String],
                                                        //prop-notes:                  OptionalList[String],
                                                        //Sale-Notes:                  OptionalList[String],
                                                        other_file_url: OptionalList[String],
                                                        house_rules: OptionalList[String],
                                                        bhome_cancellation_checkbox: OptionalList[String]
                                                      )

  @JsonCodec final case class Comments(
                                        comment_ID: Option[String],
                                        comment_post_ID: Option[String],
                                        comment_author: Option[String],
                                        comment_author_email: Option[String],
                                        comment_author_url: Option[String],
                                        comment_author_IP: Option[String],
                                        comment_date: Option[String],
                                        comment_date_gmt: Option[String],
                                        comment_content: Option[String],
                                        comment_karma: Option[String],
                                        comment_approved: Option[String],
                                        comment_agent: Option[String],
                                        comment_type: Option[String],
                                        comment_parent: Option[String],
                                        user_id: Option[String]
                                      )

  @JsonCodec final case class CommentMetaData(
                                               city: OptionalList[String],
                                               country: OptionalList[String],
                                               rating: OptionalList[String],
                                               ticket_id: OptionalList[String]
                                             )

  @JsonCodec final case class CalendarData(
                                            reservation_id: Option[String],
                                            calendar_id: Option[String],
                                            start_date: Option[String],
                                            end_date: Option[String],
                                            nights: Option[String],
                                            guests: Option[String],
                                            kids: Option[String],
                                            pets: Option[String],
                                            client_name: Option[String],
                                            client_email: Option[String],
                                            client_phone: Option[String],
                                            ticket: Option[String]
                                          )

  @JsonCodec final case class ConversationData(
                                                id: Option[String],
                                                operator_id: Option[String],
                                                user_name: Option[String],
                                                ticket_id: Option[String],
                                                email: Option[String],
                                                status_id: Option[String],
                                                dt: Option[String],
                                                ip: Option[String],
                                                invoice_status: Option[String],
                                                locked_by: Option[String],
                                                post_id: Option[String],
                                                user_surname: Option[String],
                                                accepted: Option[String],
                                                reserved: Option[String],
                                                booked: Option[String],
                                                booking_time: Option[String],
                                                reserveData: Option[String],
                                                hidden: Option[String],
                                                confirmed: Option[String],
                                                reminder: Option[String],
                                                read: Option[String],
                                                last_message: Option[String],
                                                follow_up: Option[String],
                                                client_2_reminder: Option[String],
                                                client_id: Option[String],
                                                arrival_date: Option[String],
                                                internal_notes: Option[String],
                                                category: Option[String],
                                                license: Option[String],
                                                archived: Option[String],
                                                to_check: Option[String],
                                                owner_read: Option[String],
                                                messages: Option[Map[String, Option[Map[String, Option[String]]]]]
                                              )
}