package resources

import io.circe.generic.JsonCodec

@JsonCodec final case class PropertyOwner(owner: UserData)

@JsonCodec final case class UserData(
                                      ID: String,
                                      user_login: String,
                                      user_pass: String,
                                      user_nicename: String,
                                      user_email: String,
                                      user_url: String,
                                      user_registered: String,
                                      user_activation_key: String,
                                      user_status: String,
                                      display_name: String,
                                      user_meta: UserMeta,
                                      properties: Option[Map[String, PropertyRecord]]
                                    )

@JsonCodec final case class UserMeta(
                                      nickname: Option[List[Option[String]]],
                                      first_name: Option[List[Option[String]]],
                                      last_name: Option[List[Option[String]]],
                                      wp_user_level: Option[List[Option[String]]],
                                      bhome_switch_notification: Option[List[Option[String]]],
                                      company_data: Option[List[Option[String]]],
                                      company_name: Option[List[Option[String]]],
                                      company_phone: Option[List[Option[String]]],
                                      company_street: Option[List[Option[String]]],
                                      company_city: Option[List[Option[String]]],
                                      company_zip: Option[List[Option[String]]],
                                      bhome_password_changed: Option[List[Option[String]]],
                                      bhome_password_date: Option[List[Option[String]]],
                                      ms_inquiry_first_name: Option[List[Option[String]]],
                                      ms_inquiry_last_name: Option[List[Option[String]]],
                                      ms_inquiry_email: Option[List[Option[String]]]
                                    )

@JsonCodec final case class PropertyRecord(
                                            property_data:     PropertyData,
                                            comment:           Option[Map[String, Option[Comments]]],
                                            //comment_meta:      Option[Map[String, Option[CommentMetaData]]], empty ones are as lists, others as maps. Example: 103.json
                                            calendar_data:     Option[List[Option[CalendarData]]],
                                            conversation_data: Option[Map[String, Option[ConversationData]]]
                                          )

@JsonCodec final case class PropertyData(
                                          property_id:     Int,
                                          property_fields: PropertyFields
                                        )

@JsonCodec final case class PropertyFields(
                                            post_title: Option[List[Option[String]]],
                                            post_content: Option[List[Option[String]]],
                                            post_parent: Option[List[Int]],
                                            post_status: Option[List[Option[String]]],
                                            post_url: Option[List[Option[String]]],
                                            //taxonomies: Taxonomies,
                                            //prop-nickname: Option[List[Option[String]]],
                                            listCalendar: Option[List[Option[String]]],
                                            created_by: Option[List[Option[String]]],
                                            featured_property: Option[List[Option[String]]],
                                            //License-variant: Option[List[Option[String]]],
                                            //License-text: Option[List[Option[String]]],
                                            //User-Name-BH: Option[List[Option[String]]],
                                            //User-SurName-BH: Option[List[Option[String]]],
                                            //E-Mail-BH: Option[List[Option[String]]],
                                            phone_full: Option[List[Option[String]]],
                                            owner_site: Option[List[Option[String]]],
                                            owner_name: Option[List[Option[String]]],
                                            owner_email: Option[List[Option[String]]],
                                            owner_login: Option[List[Option[String]]],
                                            //bedrooms-BH: Option[List[Option[String]]],
                                            //bedrooms-BH-Number: Option[List[Option[String]]],
                                            //bedTyle-BH: Option[List[Option[String]]],
                                            //kitchen-BH: Option[List[Option[String]]],
                                            //accomodates-BH: Option[List[Option[String]]],
                                            //accomodates-BH-Number: Option[List[Option[String]]],
                                            //bathroom-BH: Option[List[Option[String]]],
                                            //petFriendly-BH: Option[List[Option[String]]],
                                            //internet-BH: Option[List[Option[String]]],
                                            //rates-BH: Option[List[Option[String]]],
                                            //view-BH: Option[List[Option[String]]],
                                            //notes-BH: Option[List[Option[String]]],
                                            kid_friendly_description: Option[List[Option[String]]],
                                            amenities: Option[List[Option[String]]],
                                            published_per_night: Option[List[Option[String]]],
                                            published_per_night_currency: Option[List[Option[String]]],
                                            property_type: Option[List[Option[String]]],
                                            published_min_stay: Option[List[Option[String]]],
                                            headline: Option[List[Option[String]]],
                                            what_we_like_title: Option[List[Option[String]]],
                                            //what-we-like: Option[List[Option[String]]],
                                            pool_exists: Option[List[Option[String]]],
                                            kid_friendly: Option[List[Option[String]]],
                                            price_is_per_night: Option[List[Option[String]]],
                                            net_checkbox: Option[List[Option[String]]],
                                            available_for_rent_check: Option[List[Option[String]]],
                                            //pool-BH: Option[List[Option[String]]],
                                            country: Option[List[Option[String]]],
                                            //prop-inv-name: Option[List[Option[String]]],
                                            rates_table: Option[List[Option[String]]],
                                            byline_as_link: Option[List[Option[String]]],
                                            hi_res_images: Option[List[Option[String]]],
                                            first_booking_notification: Option[List[Option[String]]],
                                            new_interface: Option[List[Option[String]]],
                                            excerpt_special: Option[List[Option[String]]],
                                            show_rates_table: Option[List[Option[String]]],
                                            seo_link_footer_region: Option[List[Option[String]]],
                                            seo_link_footer_subregion: Option[List[Option[String]]],
                                            seo_link_footer_city: Option[List[Option[String]]],
                                            show_rates_table_editor: Option[List[Option[String]]],
                                            boutiqueContact: Option[List[Option[String]]],
                                            client_image_upload_done: Option[List[Option[String]]],
                                            show_floor_plans: Option[List[Option[String]]],
                                            autoaccept: Option[List[Option[String]]],
                                            around_with_description: Option[List[Option[String]]],
                                            no_past_events: Option[List[Option[String]]],
                                            no_around: Option[List[Option[String]]],
                                            influencer: Option[List[Option[String]]],
                                            social: Option[List[Option[String]]],
                                            no_exterior: Option[List[Option[String]]],
                                            dollar_value: Option[List[Option[String]]],
                                            trello: Option[List[Option[String]]],
                                            //paypal_data: Option[List[Option[String]]],
                                            ms_facts_hunter: Option[List[Option[String]]],
                                            bhome_able_to_rent: Option[List[Option[String]]],
                                            bhome_personal_or_business: Option[List[Option[String]]],
                                            bhome_presented_as_hotel: Option[List[Option[String]]],
                                            bhome_images_available: Option[List[Option[String]]],
                                            bhome_amount_of_sites: Option[List[Option[String]]],
                                            bhome_contact_person: Option[List[Option[String]]],
                                            bhome_owner_website: Option[List[Option[String]]],
                                            ms_facts_gps_descr: Option[List[Option[String]]],
                                            ms_facts_bedrooms: Option[List[Option[String]]],
                                            ms_facts_bedrooms_descr: Option[List[Option[String]]],
                                            ms_facts_bed_types: Option[List[Option[String]]],
                                            ms_facts_bed_types_descr: Option[List[Option[String]]],
                                            ms_facts_accomodate: Option[List[Option[String]]],
                                            ms_facts_accomodate_descr: Option[List[Option[String]]],
                                            ms_facts_bathrooms: Option[List[Option[String]]],
                                            ms_facts_bathrooms_descr: Option[List[Option[String]]],
                                            ms_facts_amenities: Option[List[Option[String]]],
                                            ms_facts_amenities_descr: Option[List[Option[String]]],
                                            ms_facts_rates: Option[List[Option[String]]],
                                            ms_facts_rates_descr: Option[List[Option[String]]],
                                            ms_facts_check_in: Option[List[Option[String]]],
                                            ms_facts_check_in_descr: Option[List[Option[String]]],
                                            ms_facts_deposit: Option[List[Option[String]]],
                                            ms_facts_deposit_descr: Option[List[Option[String]]],
                                            ms_facts_cancelation: Option[List[Option[String]]],
                                            ms_facts_cancelation_descr: Option[List[Option[String]]],
                                            ms_facts_min_stay: Option[List[Option[String]]],
                                            ms_facts_min_stay_descr: Option[List[Option[String]]],
                                            ms_facts_pets: Option[List[Option[String]]],
                                            ms_facts_pets_descr: Option[List[Option[String]]],
                                            ms_facts_kids: Option[List[Option[String]]],
                                            ms_facts_kids_descr: Option[List[Option[String]]],
                                            ms_facts_airport: Option[List[Option[String]]],
                                            ms_facts_airport_descr: Option[List[Option[String]]],
                                            ms_facts_visit_best: Option[List[Option[String]]],
                                            ms_facts_visit_best_descr: Option[List[Option[String]]],
                                            ms_facts_notes: Option[List[Option[String]]],
                                            ms_facts_notes_descr: Option[List[Option[String]]],
                                            ms_facts_influencer: Option[List[Option[String]]],
                                            ms_facts_social: Option[List[Option[String]]],
                                            bhome_facts_other_sites: Option[List[Option[String]]],
                                            bhome_facts_other_sites_descr: Option[List[Option[String]]],
                                            ms_facts_around: Option[List[Option[String]]],
                                            ms_facts_history: Option[List[Option[String]]],
                                            ms_facts_architect: Option[List[Option[String]]],
                                            ms_facts_press: Option[List[Option[String]]],
                                            ms_facts_seo: Option[List[Option[String]]],
                                            //bhome_property_title: Option[List[Option[String]]],
                                            ms_facts_exterior: Option[List[Option[String]]],
                                            ms_facts_interior: Option[List[Option[String]]],
                                            site_one: Option[List[Option[String]]],
                                            region: Option[List[Option[String]]],
                                            town: Option[List[Option[String]]],
                                            _yoast_wpseo_title: Option[List[Option[String]]],
                                            _yoast_wpseo_metadesc: Option[List[Option[String]]],
                                            has_events: Option[List[Option[String]]],
                                            //Thumb-Text: Option[List[Option[String]]],
                                            //Google-Maps-Lat: Option[List[Option[String]]],
                                            //Google-Maps-Lan: Option[List[Option[String]]],
                                            //Google-Maps-Zoom: Option[List[Option[String]]],
                                            //address_components: Option[List[Option[String]]],
                                            //closest_properties: Option[List[Map[String, Map[String, String]]]],
                                            //upload_main_image: Option[List[Option[String]]],
                                            bhome_property_slider: Option[List[Option[String]]],
                                            //upload_exterior_image: Option[List[Option[String]]],
                                            //upload_interior_image: Option[List[Option[String]]],
                                            //upload_slider_image: Option[List[Option[String]]],
                                            //text_image_ma: Option[List[Option[String]]],
                                            //text_image_ex: Option[List[Option[String]]],
                                            //text_image_in: Option[List[Option[String]]],
                                            //text_image_th: Option[List[Option[String]]],
                                            //text_image_slider: Option[List[Option[String]]],
                                            //text_image_in_desc: Option[List[Option[String]]],
                                            //text_image_ex_desc: Option[List[Option[String]]],
                                            //ms_search_autocomplete: Option[List[Option[String]]],
                                            agreement_name: Option[List[Option[String]]],
                                            agreement_date:              Option[List[Option[String]]],
                                            //_thumbnail_id:               Option[List[Option[String]]],
                                            security_deposit:            Option[List[Option[String]]],
                                            security_deposit_check:      Option[List[Option[String]]],
                                            check_in:                    Option[List[Option[String]]],
                                            check_out:                   Option[List[Option[String]]],
                                            cancellation:                Option[List[Option[String]]],
                                            bhome_add_quests_persons:    Option[List[Option[String]]],
                                            //additional_fees:             Option[List[Option[String]]],
                                            second_contact:              Option[List[Option[String]]],
                                            bhome_invoice_name:          Option[List[Option[String]]],
                                            bhome_invoice_surname:       Option[List[Option[String]]],
                                            bhome_invoice_email:         Option[List[Option[String]]],
                                            //bhome_season:                Option[List[Option[String]]],
                                            behome_description_title:    Option[List[Option[String]]],
                                            price_is_per_week:           Option[List[Option[String]]],
                                            traveler_notes:              Option[List[Option[String]]],
                                            security_deposit_percentage: Option[List[Option[String]]],
                                            tax_rate_check:              Option[List[Option[String]]],
                                            tax_rate_check_person:       Option[List[Option[String]]],
                                            tax_rate:                    Option[List[Option[String]]],
                                            tax_rate_person:             Option[List[Option[String]]],
                                            no_taxes_check:              Option[List[Option[String]]],
                                            bhome_rate_from:             Option[List[Option[String]]],
                                            bhome_rate_to:               Option[List[Option[String]]],
                                            price_is_per_month:          Option[List[Option[String]]],
                                            bhome_changover_check:       Option[List[Option[String]]],
                                            bhome_changover_day:         Option[List[Option[String]]],
                                            bhome_diff_weeknd_check:     Option[List[Option[String]]],
                                            bhome_diff_weeknd_rate:      Option[List[Option[String]]],
                                            bhome_diff_weeknd_thu:       Option[List[Option[String]]],
                                            bhome_diff_weeknd_fri:       Option[List[Option[String]]],
                                            bhome_diff_weeknd_sat:       Option[List[Option[String]]],
                                            bhome_diff_weeknd_sun:       Option[List[Option[String]]],
                                            bhome_add_quests_check:      Option[List[Option[String]]],
                                            bhome_add_quests_rate:       Option[List[Option[String]]],
                                            bhome_add_quests_period:     Option[List[Option[String]]],
                                            //prop-notes:                  Option[List[Option[String]]],
                                            //Sale-Notes:                  Option[List[Option[String]]],
                                            other_file_url:              Option[List[Option[String]]],
                                            house_rules:                 Option[List[Option[String]]],
                                            bhome_cancellation_checkbox: Option[List[Option[String]]]
                                          )
@JsonCodec final case class Comments(
                                      comment_ID:           Option[String],
                                      comment_post_ID:      Option[String],
                                      comment_author:       Option[String],
                                      comment_author_email: Option[String],
                                      comment_author_url:   Option[String],
                                      comment_author_IP:    Option[String],
                                      comment_date:         Option[String],
                                      comment_date_gmt:     Option[String],
                                      comment_content:      Option[String],
                                      comment_karma:        Option[String],
                                      comment_approved:     Option[String],
                                      comment_agent:        Option[String],
                                      comment_type:         Option[String],
                                      comment_parent:       Option[String],
                                      user_id:              Option[String]
                                    )
@JsonCodec final case class CommentMetaData(
                                             city:      Option[List[Option[String]]],
                                             country:   Option[List[Option[String]]],
                                             rating:    Option[List[Option[String]]],
                                             ticket_id: Option[List[Option[String]]]
                                           )
@JsonCodec final case class CalendarData(
                                          reservation_id: Option[String],
                                          calendar_id:    Option[String],
                                          start_date:     Option[String],
                                          end_date:       Option[String],
                                          nights:         Option[String],
                                          guests:         Option[String],
                                          kids:           Option[String],
                                          pets:           Option[String],
                                          client_name:    Option[String],
                                          client_email:   Option[String],
                                          client_phone:   Option[String],
                                          ticket:         Option[String]
                                        )

@JsonCodec final case class ConversationData(
                                              id:                Option[String],
                                              operator_id:       Option[String],
                                              user_name:         Option[String],
                                              ticket_id:         Option[String],
                                              email:             Option[String],
                                              status_id:         Option[String],
                                              dt:                Option[String],
                                              ip:                Option[String],
                                              invoice_status:    Option[String],
                                              locked_by:         Option[String],
                                              post_id:           Option[String],
                                              user_surname:      Option[String],
                                              accepted:          Option[String],
                                              reserved:          Option[String],
                                              booked:            Option[String],
                                              booking_time:      Option[String],
                                              reserveData:       Option[String],
                                              hidden:            Option[String],
                                              confirmed:         Option[String],
                                              reminder:          Option[String],
                                              read:              Option[String],
                                              last_message:      Option[String],
                                              follow_up:         Option[String],
                                              client_2_reminder: Option[String],
                                              client_id:         Option[String],
                                              arrival_date:      Option[String],
                                              internal_notes:    Option[String],
                                              category:          Option[String],
                                              license:           Option[String],
                                              archived:          Option[String],
                                              to_check:          Option[String],
                                              owner_read:        Option[String],
                                              messages:          Option[Map[String, Option[Map[String, Option[String]]]]]
                                            )

